### DISCUSSION TITLE
Depreciated Static Information Sensors

### DISCUSSION THREAD

**Discussion by WillCodeForCats** [WillCodeForCats/solaredge-modbus-multi#168] [Announcements]
I've decided to depreciate the following sensors because they only displayed static information that is cleanly served as attributes in each device's "Device" sensor. New attributes were already only being added to the Device sensor without a matching standalone sensor, and the integration default does not use these sensors.

* Model
* Serial Number
* Option
* Manufacturer
* Device Address
* Parent Device Address
* Sunspec DID

Version will remain as a supported sensor because it can dynamically change if a firmware update is pushed to a device. Depreciated sensors will be removed in release v2.3.0, and will no longer be part of testing or receive updates in v2.2.x releases.

To display entity attributes on the dashboard you can use the `entities` card, for example:

```
type: entities
entities:
  - type: attribute
    entity: sensor.solaredge_i1_device
    attribute: model
  - type: attribute
    entity: sensor.solaredge_i1_device
    attribute: serial_number
```

Each depreciated sensor is available as an attribute in the Device sensor:

* Model ⟶ `model`
* Serial Number ⟶ `serial_number`
* Option ⟶ `option`
* Manufacturer ⟶ `manufacturer`
* Device Address ⟶ `device_id`
* Parent Device Address ⟶ `parent_device_id`
* Sunspec DID ⟶ `sunspec_did`

There's even more possible attributes depending on the device type, too. Look at your device sensor to see what is available on your devices.
