### DISCUSSION TITLE
Energy Dashboard

### DISCUSSION THREAD

**Discussion by DougMunford** [WillCodeForCats/solaredge-modbus-multi#175] [Q&A]
I decided to populate the energy dashboard with some of the sensors from this integration. Quickly I realised that picking one or more to populate "Solar Production" was problematic and led to double counting as battery consumed by the house is also counted in the inverter AC Energy kWh sensors as the DC power from the battery is converted to AC by the inverter.

I have three inverters and two batteries, so next I tried summing the inverters less the battery export in a template and using that instead:

template:
    - sensor:
      - name: "Solar Output kWh"
        unit_of_measurement: 'kWh'
        state: >
            {% set I1 = states('sensor.solaredge_i1_ac_energy_kwh') | float %}
            {% set I2 = states('sensor.solaredge_i2_ac_energy_kwh') | float %}
            {% set I3 = states('sensor.solaredge_i3_ac_energy_kwh') | float %}
            {% set B1 = states('sensor.solaredge_b1_energy_export') | float %}
            {% set B2 = states('sensor.solaredge_b1_energy_export_2') | float %}
            {{ ((I1 + I2 + I3) - (B1 + B2)) }}
        device_class: energy
        state_class: total_increasing

This is much better but it seems it can go backwards slightly when battery usage is higher than solar production. I can see negatives when there is no sun of up to 0.08kWh per hour, not much in the grand scheme of things but looks odd on a production graph. Could this be rounding issues?

Is there a better way to get this value looking correct, or what is everyone else putting in their energy dashboard solar section if they also have a battery?

**Comment by WillCodeForCats** [comment]
Unfortunately it's a known issue that the battery import and export energy counters aren't accurate (because they reset themselves randomly) and don't behave like true energy counters.

See this wiki note: https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Known-Issues

**Reply by DougMunford** [reply]
I haven’t seen the battery counts reset entirely yet but I have experienced occasional singular 0 figures from them, which ends up throwing out the counts for the day E.g:

![19A41126-957B-4F2D-87B5-CD38CEB40A88](https://user-images.githubusercontent.com/1886703/200538623-c8b77d68-04a5-42d7-b243-6c3b8f0f2d5b.png)

**Reply by WillCodeForCats** [reply]
So what I'll do then is add an option to let the battery energy counters reset to zero, but the default will be not to allow it. That way people that have the full reset problem can choose to allow it and data like yours won't have random drop outs.

**Reply by WillCodeForCats** [reply]
Added option in PR #177

**Reply by WillCodeForCats** [reply]
[Release v2.2.7-pre.5](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.7-pre.5) should clear up those dropouts to zero but allow anyone affected by the known issue to turn the option on to let it go back to zero if they need it.

**Comment by jovana** [comment]
I have implemented the soleredge_modbus integration. And it seems to work (data is flowing in). But I have a few difficulties in creating a working dashboard. I have taken the template example from this document: https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Sensors-for-Power-and-Energy but for some reason, it is not loaded. Also have restarted HA.

I assume I missing something in the config file. Below is the completed configuration.yml file:

``` 

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Energy dashoard
template:
  - sensor:
      - name: "Power - Battery Charging"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        state: "{{ max([float(states('sensor.solaredge_battery_b1_dc_power'), 0), 0]) | abs() }}"
      - name: "Power - Battery Discharging"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        state: "{{ min([float(states('sensor.solaredge_battery_b1_dc_power'), 0), 0]) | abs() }}"

      - name: "Power - Grid Import"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        state: "{{ min([float(states('sensor.solaredge_battery_m1_ac_power'), 0), 0]) | abs() }}"
      - name: "Power - Grid Export"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        state: "{{ max([float(states('sensor.solaredge_battery_m1_ac_power'), 0), 0]) | abs() }}"

      - name: "Power - Solar Generation"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        # The net of DC power from inverter and battery, only if this is positive
        state: "{{ max([float(states('sensor.solaredge_battery_i1_dc_power'), 0) + float(states('sensor.solaredge_battery_b1_dc_power'), 0), 0]) }}"

      - name: "Power - Consumption"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        # The net of inverter and grid power
        state: "{{ float(states('sensor.solaredge_battery_i1_ac_power'), 0) - float(states('sensor.solaredge_battery_m1_ac_power'), 0) }}"


      - name: "Power - PV - Battery"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        # Battery power less anything coming from the grid, always positive
        state: "{{ max([float(states('sensor.solaredge_battery_b1_dc_power'), 0) + min([float(states('sensor.solaredge_battery_i1_dc_power'), 0), 0]), 0]) }}"
      - name: "Power - PV - Load"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        # What is being generated less what is going to the battery and what is being exported, always positive.
        state: "{{ max([float(states('sensor.power_solar_generation'), 0) - float(states('sensor.power_pv_battery'), 0) - float(states('sensor.power_grid_export'), 0), 0]) }}"
      - name: "Power - PV - Grid"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        # What is being generated less what is going to the battery and what is being consumed, always positive
        state: "{{ max([float(states('sensor.power_solar_generation'), 0) - float(states('sensor.power_pv_battery'), 0) - float(states('sensor.power_consumption'), 0), 0]) }}"

      - name: "Power - Grid - Load"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        # What is being imported less anything going to the battery, always positive
        state: "{{ max([float(states('sensor.power_grid_import'), 0) + min([float(states('sensor.solaredge_battery_i1_ac_power'), 0), 0]), 0]) }}"
      - name: "Power - Grid - Battery"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        # Grid -> Battery is I1 AC power, when negative
        # Battery -> Grid is what is being exported, if the battery is discharging
        state: "{{ max([-float(states('sensor.solaredge_battery_i1_ac_power'), 0), 0]) - (float(states('sensor.power_grid_export'), 0) if float(states('sensor.solaredge_battery_b1_dc_power'), 0) < 0 else 0) }}"

      - name: "Power - Battery - Load"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        # What is being discharged minus what is being exported, if positive
        state: "{{ max([float(states('sensor.power_battery_discharging'), 0) - float(states('sensor.power_grid_export'), 0), 0]) }}"

# Custome Tibber (pricing) integration
tibber_custom:
  # Need a newline

```

I hope someone can assist on this? Many thx!
Jo
