### DISCUSSION TITLE
Trigger automation when energy is being sent to the grid.

### DISCUSSION THREAD

**Discussion by davidecorradini** [WillCodeForCats/solaredge-modbus-multi#226] [Q&A] [answered]
Since in Italy we do not get paid much for exported solar energy, I would like to turn on a smart plug connected to an electric heating system when the solar energy is being sent to the grid, and rather use that energy to heat my house.
For instance, if the current exported power is > 1000W, turn on the smart plug. And if the exported power is < 100, then turn the smart plug off.
My SolarEdge system consists of 1 inverter and 2 batteries. I'm a bit confused by sensor names. I think their names are ambiguous.
Can somebody help me to understand what sensors do I need to take into account in order to set up the aforementioned automation?
Thank you very much! Have a nice day.
Davide

**Comment by mpredfearn** [comment, marked as answer]
@davidecorradini first of all you probably need to add some templated sensors to give you the power flows you really need for your system. I've added some documentation here https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Sensors-for-Power-and-Energy of the sensors I use. I have a single battery, but it should be relatively straightforward to add the second battery by creating a new sensor for the battery DC power which is the sum of the 2, then use it where I have used the battery power directly.

I have an automation that does exactly what you are describing. I found I had to average the exported power over time to avoid the heater constantly switching on / off - so I have an additional sensor like this:
```
sensor:
  - platform: statistics                                                        
    name: "Power - Grid Export Average"                                         
    entity_id: sensor.power_grid_export                                         
    state_characteristic: mean                                                  
    sampling_size: 10     
```
And from this I have an automation that is configured like this:
```
alias: Heater on excess solar
description: ""
trigger:
  - platform: state
    entity_id: sensor.power_grid_export_average
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.power_grid_export_average
            above: "1200"
          - condition: numeric_state
            entity_id: sensor.weather_temperature
            below: "15"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.fan_heater
            data: {}
      - conditions:
          - condition: numeric_state
            entity_id: sensor.power_grid_export_average
            below: "100"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.fan_heater
            data: {}
    default: []
mode: single
```
