### DISCUSSION TITLE
Power and energy template sensors for system with two inverters and two batteries

### DISCUSSION THREAD

**Discussion by davidecorradini** [WillCodeForCats/solaredge-modbus-multi#275] [Q&A]
Hello,
my system consists of two inverters and two batteries. Each inverter is connected to its own battery (and, of course, solar panels). I would like to add template sensors for power and energy (similarly to those provided in the wiki), however, I don't really know how implement these sensor in this scenario. The most confusing part is the fact that, as far as I know, once one battery is full and the other is not, one inverter can send AC power to the other, in order for the second inverter to charge its battery.
Can you guys help me with this?
Thank you so much!
Best,
Davide

**Comment by ocalvo** [comment]
Have the same issue.

**Reply by davidecorradini** [reply]
I think I figured out how to implement this. I will try to work on the sensors in the weekend or next week.

**Comment by jovana** [comment]
Are the inverters connected to each other by the Modbus connection? Or are they both fully standalone?
Probably you have also a grid energy meter so you know the total energy usage and total production?

**Reply by davidecorradini** [reply]
They are connected to each other, not sure with which protocol. Also I have an external meter.

**Comment by Largelos** [comment]
I don't really understand what is causing the questions?
I have 4 inverters, 3 with batteries, and there is nothing complicated here, you just need to use integration AC energy counters for solar production and Battery energy counters for battery, like on the screen:
![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/80133928/fc2a5935-8219-4d95-8676-1fe6cda0a2c0)

**Reply by davidecorradini** [reply]
These are the energy (kWh) sensors, we are also interested in power (kW) sensors. Also, with more inverters on the same line, they can "exchange" energy, for instance to charge the battery of inverter 1 with the solar power of inverter 2, and this is not taken into account in your configuration.

**Reply by Largelos** [reply]
AC and DC Power entities also exists for SE inverters and batteries, 

> they can "exchange" energy, for instance to charge the battery of inverter 1 with the solar power of inverter 2, and this is not taken into account in your configuration.

Yes, so what? What exact will "not taken into account"? Solar generated energy calculated from inverter energy counters, battery storage/export energy calculated based on battery counters.

**Reply by davidecorradini** [reply]
If they are already available, could you please tell me where can I find the PV to grid instant power? The PF to battery instant power? The battery to house instant power? Etc...

**Reply by Largelos** [reply]
PV to grid or grid to house power should be taken from grid input cable meter, "sensor.solaredge_m1_ac_power"
PV to battery and battery to house you should take from battery DC power entity, "sensor.solaredge_<id>_dc_power" positive value mean battery charging, negative mean discharge to house powering.
If you want to aggregate multiple batteries in one sensor or separate one entity to always positive "charge" and "discharge" power sensors, you can use [templates](https://www.home-assistant.io/integrations/template/)

**Comment by Ashpork** [comment]
I used to follow the configuration of battery to house, battery to grid, etc as per the big thread on HA forums, but found it overly complex to maintain. Many of the configurations on there hit problems with specific edge cases and were hard to balance, especially when the integration from SolarEdge doesn’t report these specific stats, it reports a simple set of four (in my use case)

Ive now taken the approach to just simply measure the 6 main points (in a single inverter single battery configuration). B1 dc power, i1 DC power, Solar generation (derived from battery and i1DC power), i1 ac power , m1ac (grid) and house load (derived from i1AC and grid). Using the 6 I can get as complete as picture realistically needed to maintain my system.

 I ended up asking why I would want to hypothesise what power was going from the battery to the house load vs battery to grid etc, so made the decision to make the configuration simpler and easier to maintain using the above.  Making use of Lovelace components like power-flow-plus made those estimations for me to build the visual of the flow of power.

If you’re after the battery to grid, battery to house, Solar to grid, Solar to house. The HA forums or something self made will be best. Else I’d be happy to share some configuration for my 6 focal points.

________________________________

**Reply by carsten19** [reply]
@Ashpork that would be appreciated

**Reply by Ashpork** [reply]
Have a review of this. You've made me realise I need to tidy the configuration up, so this is just a snippet of the wider config in place to help me track costs on my current Octopus Flux tariff, vs a baseline no PV/Battery tariff so that I can calculate RoI on the equipment.

I have a bunch of other configuration in place to help track generation, load, import and export daily, weekly, monthly and yearly, I included that too.

https://gist.github.com/Ashpork/f80fb0d3cb22356a12ed24734065061c

**Comment by davidecorradini** [comment]
I managed to write the sensors myself, feel free to use my configuration (probably you will need to rename sensors).
Please also note that I manually created from the GUI a sensor (helper) with the mean state of energy of the two batteries, which is not reported here.

```
template:
  - sensor:
      name: "Solaredge7.2 - Power - Batteries Power"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ float(states('sensor.solaredge7_2_b1_dc_power')) + float(states('sensor.solaredge7_2_b2_dc_power')) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Battery Charging"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ (max([float(states('sensor.solaredge7_2_b1_dc_power'), 0), 0]) | abs()) + (max([float(states('sensor.solaredge7_2_b2_dc_power'), 0), 0]) | abs())}}"
  - sensor:
      name: "Solaredge7.2 - Power - Battery Discharging"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ (min([float(states('sensor.solaredge7_2_b1_dc_power'), 0), 0]) | abs()) + (min([float(states('sensor.solaredge7_2_b2_dc_power'), 0), 0]) | abs()) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Grid Import"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ min([float(states('sensor.solaredge7_2_m1_ac_power'), 0), 0]) | abs() | round(0) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Grid Export"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ max([float(states('sensor.solaredge7_2_m1_ac_power'), 0), 0]) | abs() | round(0) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Solar Generation"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ (max([float(states('sensor.solaredge7_2_i1_dc_power'), 0) + float(states('sensor.solaredge7_2_b1_dc_power'), 0), 0]) + max([float(states('sensor.solaredge7_2_i2_dc_power'), 0) + float(states('sensor.solaredge7_2_b2_dc_power'), 0), 0])) | round(0) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Load"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ (float(states('sensor.solaredge7_2_i1_ac_power'), 0) + float(states('sensor.solaredge7_2_i2_ac_power'), 0) - float(states('sensor.solaredge7_2_m1_ac_power'), 0)) | round(0) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Solar to Battery"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ max([float(states('sensor.solaredge7_2_b1_dc_power'), 0) + min([float(states('sensor.solaredge7_2_i1_dc_power'), 0), 0]), 0]) + max([float(states('sensor.solaredge7_2_b2_dc_power'), 0) + min([float(states('sensor.solaredge7_2_i2_dc_power'), 0), 0]), 0]) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Solar to Load"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ max([float(states('sensor.solaredge7_2_power_solar_generation'), 0) - float(states('sensor.solaredge7_2_power_solar_to_battery'), 0) - float(states('sensor.solaredge7_2_power_grid_export'), 0), 0]) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Solar to Grid"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ max([float(states('sensor.solaredge7_2_power_solar_generation'), 0) - float(states('sensor.solaredge7_2_power_solar_to_battery'), 0) - float(states('sensor.solaredge7_2_power_load'), 0), 0]) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Grid to Load"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ max([float(states('sensor.solaredge7_2_power_grid_import'), 0) + min([float(states('sensor.solaredge7_2_i1_ac_power'), 0), 0]) + min([float(states('sensor.solaredge7_2_i2_ac_power_ac_power'), 0), 0]), 0]) }}"
  - sensor:
      name: "Solaredge7.2 - Power - Grid to Battery"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ max([-float(states('sensor.solaredge7_2_i1_ac_power'), 0), 0]) + max([-float(states('sensor.solaredge7_2_i2_ac_power'), 0), 0]) - (float(states('sensor.solaredge7_2_power_grid_export'), 0) if (float(states('sensor.solaredge7_2_b1_dc_power'), 0) + float(states('sensor.solaredge7_2_b2_dc_power'), 0)) < 0 else 0) }}"          
  - sensor:
      name: "Solaredge7.2 - Power - Battery to Load"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      state: "{{ max([float(states('sensor.solaredge7_2_power_battery_discharging'), 0) - float(states('sensor.solaredge7_2_power_grid_export'), 0), 0]) }}"
  - sensor:
      name: "Solaredge7.2 - Energy - Solar Generation"
      unit_of_measurement: "kWh"
      device_class: "energy"
      state_class: "total_increasing"
      state: "{{ (float(states('sensor.solaredge7_2_i1_ac_energy_kwh')) + float(states('sensor.solaredge7_2_i2_ac_energy_kwh')) + float(states('sensor.solaredge7_2_b1_energy_import')) + float(states('sensor.solaredge7_2_b2_energy_import'))- float(states('sensor.solaredge7_2_b1_energy_export')) - float(states('sensor.solaredge7_2_b2_energy_export'))) | round(3) }}"
```
