### DISCUSSION TITLE
Wiki Documentation detailing Energy Dashboard setup

### DISCUSSION THREAD

**Discussion by thargy** [WillCodeForCats/solaredge-modbus-multi#383] [General]
**Describe the feature**
Add documentation to the wiki on setting up the Energy Dashboard in HA.

**Screenshots**
![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/1908506/40f3e71b-962d-476a-9bd5-49fa0e554d88)

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: 2023.07.1
 - solaredge-modbus-multi Version: 2.3.4
 
**Additional context**
The readme advertises support for the energy dashboard, but it's not immediately obvious which sensors to add where.  For example, I'm at a loss as to which to use for the solar panels?

UPDATE:

See [this comment](https://github.com/WillCodeForCats/solaredge-modbus-multi/issues/369#issuecomment-1643322670) for latest working example.

**Comment by WillCodeForCats** [comment]
There is only one solar production sensor on the inverters: `sensor.solaredge_i*_ac_energy_kwh`

If you have a production meter that would provide another option.

**Reply by deqw** [reply]
I noticed energy reported on that sensor during the night in my Energy Dashboard. Probably energy from the home battery. So I created an integration platform energy sensor for the DC power that is produced by solar.

**Comment by WillCodeForCats** [comment]
These are on my system:

<img width="1051" alt="Screenshot 2023-07-19 at 10 19 20 AM" src="https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/48533968/1a91cee4-7a9d-4beb-af4b-9aac64275bea">

<img width="374" alt="Screenshot 2023-07-19 at 10 19 36 AM" src="https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/48533968/3f6b4cf2-af82-4ab8-b850-1bcc7394169a">

**Comment by Ashpork** [comment]
On a system with a SolarEdge DC based battery, thats not quite true. As the battery is DC connected, it goes through the inverter and its output appears here too as a combined generated value.

For example my system my I1 AC energy kWh shows the below:

[Image.png.png]

________________________________

**Reply by deqw** [reply]
Ah see my note above (just read this now, sorry)....

**Comment by WillCodeForCats** [comment]
Yeah I don't have any experience with how that entity interacts with battery.

**Comment by Ashpork** [comment]
No worries at all.

 This is my configuration for a single inverter, single battery configuration if it helps anyone.

https://gist.github.com/Ashpork/f80fb0d3cb22356a12ed24734065061c
________________________________

**Reply by sentience** [reply]
Using this configuration, here's how I've configured my Energy Dashboard:

![CleanShot 2023-09-03 at 23 29 25@2x](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/89772/e460c5e1-7583-435b-bb97-b3a1c4dd28dc)

I hope the "Daily" meters are the right ones to be using here. I notice the Energy Dashboard has week, month, and year views, and your configuration includes meters for those time periods as well. Is there something I'm still missing?

**Comment by thargy** [comment]
> No worries at all. This is my configuration for a single inverter, single battery configuration if it helps anyone. [gist.github.com/Ashpork/f80fb0d3cb22356a12ed24734065061c](https://gist.github.com/Ashpork/f80fb0d3cb22356a12ed24734065061c)

Perfect! I have one battery per inverter, so I should be able to adapt.

**Comment by WillCodeForCats** [comment]
> No worries at all. This is my configuration for a single inverter, single battery configuration if it helps anyone. https://gist.github.com/Ashpork/f80fb0d3cb22356a12ed24734065061c

Added to [wiki/YAML-Sample-Configurations](https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/YAML-Sample-Configurations)

**Comment by thargy** [comment]
> No worries at all. This is my configuration for a single inverter, single battery configuration if it helps anyone. [gist.github.com/Ashpork/f80fb0d3cb22356a12ed24734065061c](https://gist.github.com/Ashpork/f80fb0d3cb22356a12ed24734065061c)

As this is in the Wiki, might want to re-indent [Line 50](https://gist.github.com/Ashpork/f80fb0d3cb22356a12ed24734065061c#file-ha-power-sensors-yaml-L50).

**Comment by requiemmg** [comment]
Thanks, I'll give it a shot. I just got my batteries a week ago, everything was easy before. I now switched from Solaredge Modbus to Modbus multi and redid my dashboards, but energy dashboard is giving me a headache.

I have this in my energy export/import from/to grid:
![grafik](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/11157808/103448eb-dfc0-4576-82a1-273505e44d06)

result is an empty energy usage graph, but the entities themselves show their expected values from the modbus and also the history of the entities is there.

Even more strange:
![grafik](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/11157808/6a3278dc-adb8-4fe8-97d3-e4d712098d51)

I have never excluded anything from the recorder and wonder what happened here...

**Comment by thargy** [comment]
> I have never excluded anything from the recorder and wonder what happened here...

It needs at least 2 data points to generate statistics and can take up to 2 hours.

Also, if you see the [gists](https://gist.github.com/thargy/f9713cd6c06bc77a22a4b323ed0f83af), you'll note that you can't just add the Inverters AC Energy to get the Solar Panel production.  That is because it also includes any energy coming from the battery.

Instead, we create a new sensor which uses the inverter's DC power and removes the battery's contribution to calculate the remainder, which, presumably, is what is being generated by solar.

**Comment by thargy** [comment]
I have made an updated version of the above gist for 2 inverters/2 batteries, also fixed several issues and made it easier to deploy as a package:

https://gist.github.com/thargy/f9713cd6c06bc77a22a4b323ed0f83af

In current testing, it is working very well.  Once I have a few days of comparables, I may consider making the package configurable so that you can specify combinations of inverters/panels/batteries and have it create the summary statistics for you.  That is doable in YAML, though you wouldn't have the intermediate sensors.  In the meantime, if you are pretty familiar with YAML, it provides enough insight to be converted for any installation.

![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/1908506/47917746-f1be-4c3c-82d4-8efa6010ac5f)
![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/1908506/fcd763c3-8cff-4412-bb2f-ab449faf40fc)

**Comment by requiemmg** [comment]
> > I have never excluded anything from the recorder and wonder what happened here...
> 
> It needs at least 2 data points to generate statistics and can take up to 2 hours.
> 
> Also, if you see the [gists](https://gist.github.com/thargy/f9713cd6c06bc77a22a4b323ed0f83af), you'll note that you can't just add the Inverters AC Energy to get the Solar Panel production. That is because it also includes any energy coming from the battery.
> 
> Instead, we create a new sensor which uses the inverter's DC power and removes the battery's contribution to calculate the remainder, which, presumably, is what is being generated by solar.

Thanks, this is what I was looking for.
I had it runing with the new config for >24 hours and the parameters are still not shown.
Nevermind, I think my database has some nasty leftovers and duplicate entries which might cause issues. I'll use this as an opportunity to start with a fresh HA installation and restore only my needed addons which are a bit more complex to configure from a partial backup. And I'll use an SSD instead of SD card....

**Comment by thargy** [comment]
> Thanks, this is what I was looking for. I had it runing with the new config for >24 hours and the parameters are still not shown. Nevermind, I think my database has some nasty leftovers and duplicate entries which might cause issues. I'll use this as an opportunity to start with a fresh HA installation and restore only my needed addons which are a bit more complex to configure from a partial backup. And I'll use an SSD instead of SD card....

The energy dashboard is particularly sensitive about having the correct `device_class` and `state_class` set for each sensor (you'll note [my gist explicitly sets them for this reason](https://gist.github.com/thargy/f9713cd6c06bc77a22a4b323ed0f83af#file-solaredge-yaml-L255-L286)).

Yeah, I dumped my Pi and changed is to be a second Zigbee2MQTT coordinator for my sensor network (which is so spammy it made the primary network unstable).  I replaced it with a relatively cheap [Imported N305 NUC](https://www.aliexpress.com/item/1005004009585758.html?spm=a2g0o.order_list.order_list_main.59.21ef1802qEUNpX) which has been rock solid ever since (and seriously overpowered).

However, you can do a lot of clean-up via judicious use of the "System-> Devices & Services -> Entities" and "Developer Tools-> Statistics" pages without throwing away all the juicy data, if you're motivated sufficiently!

**Comment by requiemmg** [comment]
Thanks, I know, but somehow I have a situation where some entities are duplicate, some are not working properly, I think something got messed up in my database and I like to start over with a fresh installation. Just hope that all my backups are working properly.

**Comment by requiemmg** [comment]
Hi again...I just did a fresh reinstall of Home Assistant and set up Solaredge Modbus Multi. As I have a single inverter/single battery system, I tried @Ashpork 's config file. I tried putting it in my packages dir as well as in the config.yaml, both give no errors and the sensors will show up but not the utility meters. Any idea why?
Second idea would be editing @thargy 's config to fit my needs, but I'm not sure if i am capable to do so...

Edit: Nevermind, thought they'd appear as meters. I just edited @thargy's config to be used with my setup, went flawlessly, should be working now.

**Comment by Rai-Rai** [comment]
Hi, I'd like to jump in here.
I'm using the latest home hub Inverter with connected 48V Battery.

The Power-Flow-Card-Plus is working perfectly, thanks to @thargy for his great example.

Also, on the Home Assistant Energy dashboard the Grid Import/Export is working with SolarEdge M1 Imported/Exported kWh.

What is not working is the correct display of photovoltaic and battery energy. The reason for this is that all the energy that goes into (or out of) the battery is also recorded by the I1 AC kWh energy sensor.
The result is that if the battery is discharging during night it is recorded as if IN ADDITION the photovoltaic is generating energy. (which of course also doubles the building consumption)
Additionally you can clearly see the conversion losses (0,61kWh exported from battery results in 0,48kWh for the house)

Just removing the battery from the energy dashboard would likely resolve this, but I'd really like to see it there....
![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/2023869/4da09bb8-0782-4d3e-b743-772b26023ce9)
At 1-2 AM there is absolutely no sun...



Heres a picture of the wrong powerFlow:
![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/2023869/7eecc76d-f381-4cea-8a86-579a28f341cd)
The real House consumption was 10kWh. due to battery discharge going through the inverter it's nearly double the value

**Reply by thargy** [reply]
Sorry, I've moved on to other projects (custom hot water tank/boiler controller with ESP32), so I'm not in this headspace.  Honestly, I almost exclusively use the Power-Flow-Card-Plus which has been awesome for me, and not paid any attention to the Energy Dashboard, beyond my initial setup.  Sounds like I'll have to come back and have a look again when I have the capacity.

**Comment by sentience** [comment]
@Rai-Rai Following an example found elsewhere (sorry, don't have the link immediately to hand), I believe I've solved this by creating synthetic sensors based on the right combination of sensors provided by solaredge-modbus-multi. To do this, I added the following to the bottom of my HomeAsssistant configuration.yaml file:

```yaml
template:
  - sensor:
      - name: "Solar Panel Production W"
        unique_id: solar_panel_production_w
        unit_of_measurement: "W"
        icon: mdi:solar-power
        state: >
          {% set i1_dc_power = states('sensor.solaredge_i1_dc_power') | float(0) %}
          {% set b1_dc_power = states('sensor.solaredge_b1_dc_power') | float(0) %}
          {% if (i1_dc_power + b1_dc_power <= 0) %}
            0
          {% else %}
            {{ (i1_dc_power + b1_dc_power) }}
          {% endif %}
        availability: >
          {{ states('sensor.solaredge_i1_dc_power') | is_number and states('sensor.solaredge_b1_dc_power') | is_number }}
      - name: "Solar House Consumption W"
        unique_id: solar_house_consumption_w
        unit_of_measurement: "W"
        icon: mdi:home
        state: >
          {% set i1_ac_power = states('sensor.solaredge_i1_ac_power') | float(0) %}
          {% set m1_ac_power = states('sensor.solaredge_m1_ac_power') | float(0) %}
          {% if (i1_ac_power - m1_ac_power <= 0) %}
            0
          {% else %}
            {{ (i1_ac_power - m1_ac_power) }}
          {% endif %}
        availability: >
          {{ states('sensor.solaredge_i1_ac_power') | is_number and states('sensor.solaredge_m1_ac_power') | is_number }}
      - name: Solar Inverter Consumption w
        unique_id: solar_inverter_consumption_w
        unit_of_measurement: "W"
        icon: mdi:mdi:home-lightning-bolt-outline
        state: >
          {% set i1_ac_power = states('sensor.solaredge_i1_ac_power') | float(0) %}
          {% set i1_dc_power = states('sensor.solaredge_i1_dc_power') | float(0) %}
          {% if (i1_ac_power > i1_dc_power < 0) %}
            {{ (i1_ac_power - i1_dc_power)| round(2) }}
          {% else %}
            {{ ( i1_dc_power - i1_ac_power)| round(2)}}
          {% endif %}
        availability: >
          {{ states('sensor.solaredge_i1_ac_power') | is_number and states('sensor.solaredge_i1_dc_power') | is_number }}
      - name: "Solar Imported Power W"
        unique_id: solar_imported_power_w
        unit_of_measurement: "W"
        icon: mdi:transmission-tower-export
        state: >
          {% set m1_ac_power = states('sensor.solaredge_m1_ac_power') | float(0) %}
          {% if (m1_ac_power < 0) %}
            {{ (m1_ac_power * -1) }}
          {% else %}
            0
          {% endif %}
        availability: >
          {{ states('sensor.solaredge_m1_ac_power') | is_number}}
      - name: "Solar Exported Power W"
        unique_id: solar_exported_power_w
        unit_of_measurement: "W"
        icon: mdi:transmission-tower-import
        state: >
          {% set m1_ac_power = states('sensor.solaredge_m1_ac_power') | float(0) %}
          {% if (m1_ac_power > 0) %}
            {{ (m1_ac_power) }}
          {% else %}
            0
          {% endif %}
        availability: >
          {{ states('sensor.solaredge_m1_ac_power') | is_number }}
      - name: "Home - Fossil Fuel"
        unique_id: home_fossil_fuel
        unit_of_measurement: "%"
        icon: mdi:barrel
        state: >
          {% set home_renewables = states('sensor.home_renewables') | float(0) %}
          {{ (100 - home_renewables) }}
        availability: >
          {{ states('sensor.home_renewables') | is_number }}

sensor:
  - platform: integration
    source: sensor.solar_panel_production_w
    method: left
    unit_prefix: k
    name: solar_panel_production_kwh
  - platform: integration
    source: sensor.solar_house_consumption_w
    method: left
    unit_prefix: k
    name: solar_house_consumption_kwh
  - platform: integration
    source: sensor.solar_imported_power_w
    method: left
    unit_prefix: k
    name: solar_imported_power_kwh
  - platform: integration
    source: sensor.solar_exported_power_w
    method: left
    unit_prefix: k
    name: solar_exported_power_kwh

utility_meter:
  solar_panel_production_daily:
    source: sensor.solar_panel_production_kwh
    name: Solar Panel Production Daily
    cycle: daily
  solar_house_consumption_daily:
    source: sensor.solar_house_consumption_kwh
    name: Solar House Consumption Daily
    cycle: daily
  solar_imported_power_daily:
    source: sensor.solar_imported_power_kwh
    name: Solar Imported Power Daily
    cycle: daily

  solar_exported_power_daily:
    source: sensor.solar_exported_power_kwh
    name: Solar Exported Power Daily

  solar_imported_power_weekly:
    source: sensor.solar_imported_power_kwh
    name: Solar Imported Power Weekly
    cycle: weekly
  solar_house_consumption_weekly:
    source: sensor.solar_house_consumption_kwh
    name: Solar House Consumption Weekly
    cycle: weekly
  solar_panel_production_weekly:
    source: sensor.solar_panel_production_kwh
    name: Solar Panel Production Weekly
    cycle: weekly
  solar_exported_power_weekly:
    source: sensor.solar_exported_power_kwh
    name: Solar Exported Power Weekly
    cycle: weekly


  solar_imported_power_monthly:
    source: sensor.solar_imported_power_kwh
    name: Solar Imported Power Monthly
    cycle: monthly
  solar_house_consumption_monthly:
    source: sensor.solar_house_consumption_kwh
    name: Solar House Consumption Monthly
    cycle: monthly
  solar_panel_production_monthly:
    source: sensor.solar_panel_production_kwh
    name: Solar Panel Production Monthly
    cycle: monthly
  solar_exported_power_monthly:
    source: sensor.solar_exported_power_kwh
    name: Solar Exported Power Monthly
    cycle: monthly

  solar_imported_power_yearly:
    source: sensor.solar_imported_power_kwh
    name: Solar Imported Power Yearly
    cycle: yearly
  solar_house_consumption_yearly:
    source: sensor.solar_house_consumption_kwh
    name: Solar House Consumption Yearly
    cycle: yearly
  solar_panel_production_yearly:
    source: sensor.solar_panel_production_kwh
    name: Solar Panel Production Yearly
    cycle: yearly
  solar_exported_power_yearly:
    source: sensor.solar_exported_power_kwh
    name: Solar Exported Power Yearly
    cycle: yearly
```

…and then I can use these sensors in power-flow-card-plus. This is my configuration, which includes a MyEnegi EV charger.

```yaml
type: custom:power-flow-card-plus
title: Power Flow
entities:
  home:
    entity: sensor.solar_house_consumption_w
    color_icon: true
    color_value: true
  fossil_fuel_percentage:
    entity: sensor.home_fossil_fuel
    icon: mdi:leaf
    color_icon: true
    display_zero: true
    name: Green Import
    state_type: percentage
    color_value: true
    display_zero_state: true
    secondary_info:
      template: |-
        {% set grid_power = states('sensor.solaredge_m1_ac_power') | float(0) %}
        {% set green_pct = states('sensor.home_renewables') | float(0) %}
        {% if (grid_power < 0) %}
          {{ (-grid_power * green_pct / 100) | round(0) }} W
        {% endif %}
      display_zero: false
      color_value: true
    unit_white_space: false
  grid:
    name: Grid
    entity: sensor.solaredge_m1_ac_power
    display_state: one_way_no_zero
    color_circle: true
    invert_state: true
    secondary_info:
      decimals: 2
      display_zero: false
      template: >
        {% set grid_power = states('sensor.solaredge_m1_ac_power') | float(0) %}

        {% set grid_buy_price = states('sensor.home_general_price') | float(0)
        %}

        {% set grid_sell_price = states('sensor.home_feed_in_price') | float(0)
        %}

        {% if grid_power < 0 %}
          {{ (grid_buy_price * 100) | round(0) }} ¢
        {% elif grid_power > 0 %}
          {{ (grid_sell_price * 100) | round(0) }} ¢
        {% else %}

        {% endif %}
  solar:
    icon: mdi:solar-panel-large
    entity: sensor.solar_panel_production_w
    color_value: true
    color_icon: true
  battery:
    name: Battery
    entity: sensor.solaredge_b1_dc_power
    display_state: one_way_no_zero
    color_icon: true
    color_circle: true
    invert_state: true
    state_of_charge: sensor.solaredge_b1_state_of_energy
    color_state_of_charge_value: true
  individual1:
    entity: sensor.myenergi_my_home_power_charging
    secondary_info:
      entity: sensor.maple_battery
      unit_of_measurement: '%'
    display_zero: true
    color_value: true
    color_icon: false
    display_zero_state: false
  individual2:
    color_value: false
clickable_entities: true
display_zero_lines:
  mode: transparency
  transparency: 80
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 10000
min_expected_power: 0.01
watt_threshold: 750
dashboard_link: /energy
dashboard_link_label: Energy Summary
```
