### ISSUE TITLE
New Device Classes in HA 2023.04

### ISSUE THREAD

**Issue by ryanm101** [WillCodeForCats/solaredge-modbus-multi#282]
https://www.home-assistant.io/blog/2023/04/05/release-20234/#other-noteworthy-changes

```
[@emontnemery](https://github.com/emontnemery) added energy storage and volume storage device classes; 
these will allow differentiating between, for example, consumed energy versus stored energy in a battery.
```
battery: Percentage of battery that is left in %
energy: Energy in Wh, kWh, MWh, MJ, or GJ
energy_storage: Stored energy in Wh, kWh, MWh, MJ, or GJ

I'm thinking some of the devices should possibly use the new class

**Comment by ryanm101** [comment]
```
sensor.solaredge_b1_available_energy:
      device_class: energy_storage
sensor.solaredge_b1_maximum_energy:
      device_class: energy_storage
```
